CREATE TABLE MEMBER (
	seq BIGINT AUTO_INCREMENT,
	email VARCHAR(65) NOT NULL UNIQUE,
	password VARCHAR(65) NOT NULL,
	name VARCHAR(45) NOT NULL,
	mobile VARCHAR(15) NOT NULL,
	authority ENUM('MEMBER', 'ADMIN') DEFAULT 'MEMBER',
	termsAgree TINYINT DEFAULT 0,
	createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	modifiedAt DATETIME,
	deletedAt DATETIME,
	PRIMARY KEY(seq)
);

CREATE TABLE FILE_INFO (
    seq BIGINT AUTO_INCREMENT,
    gid VARCHAR(45) NOT NULL,
    location VARCHAR(45),
    fileName VARCHAR(100) NOT NULL,
    extension VARCHAR(45),
    contentType VARCHAR(65),
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    modifiedAt DATETIME,
    deletedAt DATETIME,
    createdBy BIGINT,
    modifiedBy BIGINT,
    PRIMARY KEY(seq),
    FOREIGN KEY (createdBy) REFERENCES MEMBER(seq)
);